### ISSUE TITLE
[Request] Automatically take screenshot when test failed

### ISSUE THREAD

**Issue by feryardiant** [adonisjs/vow-browser#5]
I thought it would be really useful if `vow-browser` also have this feature so basically we could actually see what happen when the testing's failed. Here's the simple use case,

- I'm build a SPA with a popular front-end framework (e.g. Vue, Reack, etc)
- I expecting to see an element with `Some text` on the page
- For some reason the testing got failed because the element returns empty text
- But it should works because when I test it live on browser, I saw it there

```
Visit Home Page
  ✖ See Some Text (6s)


 ERRORS 

1. See Some Text
expected '' to deeply equal 'Some Text'
"" => "Some Text"

 FAILED 

total       : 1
failed      : 1
time        : 6s
```

Info : Inspired by [Laravel Dusk](https://github.com/laravel/dusk/blob/3.0/src/Concerns/ProvidesBrowser.php#L62-L81).

Any thoughts?

**Comment by thetutlage** [comment]
When building an SPA, I suggest using tooling provided by Vue. Using adonis testing libraries, will not get you so far.

Anyways I am still going to add support to turn on screenshots for failed tests.
